#!/usr/bin/env python3
"""Export daily operations roster to data/operations_roster.json.

Source: data/covalent.json, data/tronox.json, data/csbp.json (generated by
        parse_rapidcrews.py and subsequent pipeline steps).

Each shutdown roster entry already carries worker start/end dates, role, mobile,
hire_company, and personnel_id.  This script consolidates all three files into a
single per-worker view with grouped assignments, ready for the ops-roster tab.

The xpbi02 PersonnelRosterView in the macro workbook currently contains data for
non-Kwinana sites only (e.g. Iron Bridge/Fortescue), so we read it as a secondary
source: any Kwinana-matching rows it contains are merged in, giving per-day
granularity when available.
"""
from __future__ import annotations

import datetime as dt
import json
import pathlib
import re
from typing import Any

import openpyxl

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA_DIR = REPO_ROOT / "data"
RAW_FILE = DATA_DIR / "raw" / "Rapidcrews Macro Data.xlsx"
OUT_FILE = DATA_DIR / "operations_roster.json"

COMPANY_FILES = [
    DATA_DIR / "covalent.json",
    DATA_DIR / "tronox.json",
    DATA_DIR / "csbp.json",
]

ROSTER_VIEW_SHEET = "xpbi02 PersonnelRosterView"
PERSONNEL_SHEET = "xll01 Personnel"

KWINANA_TERMS = (
    "covalent", "tronox", "csbp", "tianqi",
    "kleenheat", "kwinana", "naan", "kpf",
)

ALIASES: dict[str, list[str]] = {
    "Job No": ["Job No", "JobNo", "Job Number", "JobId", "Job Id", "QuoteNo", "OrderNo"],
    "Client": ["Client", "ClientId", "Client Id", "ClientName", "Client Name"],
    "Site": ["Site", "SiteName", "Site Name", "Location"],
    "Personnel Id": ["Personnel Id", "PersonnelId", "Personnel ID", "Employee Id", "EmployeeID"],
    "Schedule Date": ["Schedule Date", "ReportDate", "Date", "Roster Date", "Shift Date"],
    "Schedule Type": ["Schedule Type", "ScheduleType", "Shift", "Shift Type"],
    "IsOnLocation": ["IsOnLocation", "OnSite", "On Site", "Is On Location"],
    "Given Names": ["Given Names", "Given Name", "First Name", "FirstName"],
    "Surname": ["Surname", "Last Name", "Family Name"],
    "Role": ["Trade", "Discipline", "Primary Role", "Role", "Position"],
    "Mobile": ["Mobile", "Mobile Phone", "Mobile No", "Phone", "Contact"],
    "Hire Company": ["Hire Company", "Hiring Company", "Labour Hire Company", "Labour Hire", "Company"],
}


def _clean(value: Any) -> str:
    return re.sub(r"\s+", " ", str(value or "").replace("\xa0", " ")).strip()


def _norm(value: Any) -> str:
    return re.sub(r"[^a-z0-9]+", "", _clean(value).lower())


def _headers(ws) -> dict[str, int]:
    try:
        header = list(next(ws.iter_rows(max_row=1, values_only=True)))
    except StopIteration:
        return {}
    return {_clean(h): i for i, h in enumerate(header) if _clean(h)}


def _find_col(headers: dict[str, int], canonical: str, required: bool = True) -> int | None:
    normal = {_norm(k): v for k, v in headers.items()}
    for alias in ALIASES.get(canonical, [canonical]):
        if _norm(alias) in normal:
            return normal[_norm(alias)]
    if required:
        raise KeyError(f"Missing required column {canonical!r}; available: {', '.join(headers)}")
    return None


def _get(row: tuple[Any, ...], idx: int | None) -> Any:
    if idx is None or idx >= len(row):
        return None
    return row[idx]


def _date(value: Any) -> str:
    if isinstance(value, dt.datetime):
        return value.date().isoformat()
    if isinstance(value, dt.date):
        return value.isoformat()
    text = _clean(value)
    if not text:
        return ""
    for fmt in ("%Y-%m-%d", "%d/%m/%Y", "%d-%m-%Y", "%m/%d/%Y"):
        try:
            return dt.datetime.strptime(text[:10], fmt).date().isoformat()
        except ValueError:
            pass
    return ""


def _contiguous_ranges(sorted_dates: list[str]) -> list[tuple[str, str]]:
    """Split a sorted list of ISO dates into (start, end) contiguous segments."""
    if not sorted_dates:
        return []
    ranges: list[tuple[str, str]] = []
    seg_start = sorted_dates[0]
    prev = dt.date.fromisoformat(sorted_dates[0])
    for d_str in sorted_dates[1:]:
        d = dt.date.fromisoformat(d_str)
        if (d - prev).days > 1:
            ranges.append((seg_start, prev.isoformat()))
            seg_start = d_str
        prev = d
    ranges.append((seg_start, prev.isoformat()))
    return ranges


def _parse_bool(value: Any) -> bool:
    if isinstance(value, bool):
        return value
    if isinstance(value, (int, float)):
        return bool(value)
    return _clean(value).lower() in {"1", "true", "yes", "y", "on", "onsite", "on site"}


def _resolve_sheet(wb: openpyxl.Workbook, canonical: str) -> str | None:
    if canonical in wb.sheetnames:
        return canonical
    target = _norm(canonical)
    for name in wb.sheetnames:
        n = _norm(name)
        if n == target or re.fullmatch(rf"{re.escape(target)}\d+", n):
            return name
    return None


def _is_kwinana(client: str, site: str) -> bool:
    combined = f"{client} {site}".lower()
    return any(term in combined for term in KWINANA_TERMS)


# ---------------------------------------------------------------------------
# Primary source: data/covalent.json, tronox.json, csbp.json
# ---------------------------------------------------------------------------

def _load_from_json_files() -> dict[str, dict[str, Any]]:
    """Return pid -> worker record with assignments built from company JSON files."""
    by_pid: dict[str, dict[str, Any]] = {}

    for path in COMPANY_FILES:
        if not path.exists():
            continue
        try:
            payload = json.loads(path.read_text())
        except Exception as exc:
            print(f"export_operations_roster: could not read {path.name}: {exc}")
            continue

        company = _clean(payload.get("company", path.stem))
        for shutdown in payload.get("shutdowns", []) or []:
            job_no = _clean(shutdown.get("id", ""))
            site   = _clean(shutdown.get("site", company))
            client = company
            for worker in shutdown.get("roster", []) or []:
                pid    = _clean(worker.get("personnel_id", ""))
                name   = _clean(worker.get("name", ""))
                if not name:
                    continue
                start  = _clean(worker.get("start") or shutdown.get("start_date", ""))
                end    = _clean(worker.get("end")   or shutdown.get("end_date",   ""))
                if not start or not end:
                    continue

                key = pid if pid else _norm(name)
                if key not in by_pid:
                    by_pid[key] = {
                        "personnel_id": pid,
                        "name":         name,
                        "role":         _clean(worker.get("role", "")),
                        "mobile":       _clean(worker.get("mobile", "")),
                        "hire_company": _clean(worker.get("hire_company", "")),
                        "assignments":  [],
                    }
                rec = by_pid[key]
                # Keep the most complete name/role/mobile we've seen.
                if len(name) > len(rec["name"]):
                    rec["name"] = name
                if worker.get("role"):
                    rec["role"] = _clean(worker["role"])
                if worker.get("mobile"):
                    rec["mobile"] = _clean(worker["mobile"])
                if worker.get("hire_company"):
                    rec["hire_company"] = _clean(worker["hire_company"])

                rec["assignments"].append({
                    "job_no":         job_no,
                    "client":         client,
                    "site":           site,
                    "start":          start,
                    "end":            end,
                    "schedule_type":  _clean(worker.get("shift", "Day Shift")) or "Day Shift",
                    "is_on_location": True,
                })

    return by_pid


# ---------------------------------------------------------------------------
# Secondary source: xpbi02 PersonnelRosterView (macro workbook)
# Only used if rows match Kwinana terms — provides per-day granularity when
# the macro workbook covers Kwinana sites.
# ---------------------------------------------------------------------------

def _load_personnel_from_wb(wb: openpyxl.Workbook) -> dict[str, dict[str, str]]:
    sheet = _resolve_sheet(wb, PERSONNEL_SHEET)
    if not sheet:
        return {}
    ws = wb[sheet]
    headers = _headers(ws)
    pid_i    = _find_col(headers, "Personnel Id", required=False)
    first_i  = _find_col(headers, "Given Names",  required=False)
    last_i   = _find_col(headers, "Surname",       required=False)
    role_i   = _find_col(headers, "Role",          required=False)
    mobile_i = _find_col(headers, "Mobile",        required=False)
    hire_i   = _find_col(headers, "Hire Company",  required=False)

    out: dict[str, dict[str, str]] = {}
    for row in ws.iter_rows(min_row=2, values_only=True):
        pid = _clean(_get(row, pid_i))
        if not pid:
            continue
        first = _clean(_get(row, first_i))
        last  = _clean(_get(row, last_i))
        out[pid] = {
            "name":         f"{first} {last}".strip(),
            "role":         _clean(_get(row, role_i)),
            "mobile":       _clean(_get(row, mobile_i)),
            "hire_company": _clean(_get(row, hire_i)),
        }
    return out


def _load_kwinana_from_roster_view(
    wb: openpyxl.Workbook,
    personnel: dict[str, dict[str, str]],
) -> list[dict[str, Any]]:
    """Read PersonnelRosterView; return Kwinana assignments grouped by (pid, job)."""
    sheet = _resolve_sheet(wb, ROSTER_VIEW_SHEET)
    if not sheet:
        return []

    ws = wb[sheet]
    headers = _headers(ws)
    job_i    = _find_col(headers, "Job No",        required=False)
    client_i = _find_col(headers, "Client",        required=False)
    site_i   = _find_col(headers, "Site",          required=False)
    pid_i    = _find_col(headers, "Personnel Id",  required=False)
    date_i   = _find_col(headers, "Schedule Date", required=False)
    sched_i  = _find_col(headers, "Schedule Type", required=False)
    onsite_i = _find_col(headers, "IsOnLocation",  required=False)

    if date_i is None or pid_i is None:
        return []

    groups: dict[tuple[str, str], dict[str, Any]] = {}
    for row in ws.iter_rows(min_row=2, values_only=True):
        if not row or not any(row):
            continue
        pid = _clean(_get(row, pid_i))
        day = _date(_get(row, date_i))
        if not pid or not day:
            continue
        client = _clean(_get(row, client_i)) if client_i is not None else ""
        site   = _clean(_get(row, site_i))   if site_i   is not None else ""
        if not _is_kwinana(client, site):
            continue
        job   = _clean(_get(row, job_i))   if job_i   is not None else ""
        sched = _clean(_get(row, sched_i)) if sched_i is not None else ""
        key   = (pid, job)
        if key not in groups:
            groups[key] = {
                "pid": pid, "job": job, "client": client, "site": site,
                "dates": set(), "sched_types": {}, "on_location_count": 0,
            }
        g = groups[key]
        g["dates"].add(day)
        if sched:
            g["sched_types"][sched] = g["sched_types"].get(sched, 0) + 1
        if _parse_bool(_get(row, onsite_i)):
            g["on_location_count"] += 1

    assignments: list[dict[str, Any]] = []
    for g in groups.values():
        if not g["dates"]:
            continue
        sorted_dates = sorted(g["dates"])
        sched = (
            max(g["sched_types"], key=g["sched_types"].get)
            if g["sched_types"] else "Day Shift"
        )
        p = personnel.get(g["pid"], {})
        for seg_start, seg_end in _contiguous_ranges(sorted_dates):
            assignments.append({
                "pid":            g["pid"],
                "name":           p.get("name", ""),
                "role":           p.get("role", ""),
                "mobile":         p.get("mobile", ""),
                "hire_company":   p.get("hire_company", ""),
                "job_no":         g["job"],
                "client":         g["client"],
                "site":           g["site"],
                "start":          seg_start,
                "end":            seg_end,
                "schedule_type":  sched,
                "is_on_location": g["on_location_count"] > 0,
            })
    return assignments


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> int:
    # Primary: build from covalent/tronox/csbp JSON files.
    by_pid = _load_from_json_files()

    # Secondary: merge in any Kwinana rows from the macro workbook's roster view.
    wb_kwinana_count = 0
    if RAW_FILE.exists():
        wb = openpyxl.load_workbook(RAW_FILE, data_only=True, read_only=True)
        try:
            personnel   = _load_personnel_from_wb(wb)
            wb_assigns  = _load_kwinana_from_roster_view(wb, personnel)
        finally:
            wb.close()

        for a in wb_assigns:
            pid = a["pid"]
            key = pid if pid else _norm(a["name"])
            if key not in by_pid:
                by_pid[key] = {
                    "personnel_id": pid,
                    "name":         a["name"],
                    "role":         a["role"],
                    "mobile":       a["mobile"],
                    "hire_company": a["hire_company"],
                    "assignments":  [],
                }
            by_pid[key]["assignments"].append({
                "job_no":        a["job_no"],
                "client":        a["client"],
                "site":          a["site"],
                "start":         a["start"],
                "end":           a["end"],
                "schedule_type": a["schedule_type"],
                "is_on_location": a["is_on_location"],
            })
            wb_kwinana_count += 1

    if not by_pid:
        print("export_operations_roster: no roster data found; skipped")
        return 0

    workers = sorted(by_pid.values(), key=lambda w: w["name"])
    total_assignments = sum(len(w["assignments"]) for w in workers)

    payload = {
        "generated_at": dt.datetime.utcnow().replace(microsecond=0).isoformat() + "Z",
        "worker_count": len(workers),
        "workers":      workers,
    }
    OUT_FILE.write_text(json.dumps(payload, indent=2))
    msg = (
        f"export_operations_roster: wrote {len(workers)} workers "
        f"({total_assignments} assignments) to {OUT_FILE.relative_to(REPO_ROOT)}"
    )
    if wb_kwinana_count:
        msg += f" [{wb_kwinana_count} from macro workbook PersonnelRosterView]"
    print(msg)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
